name: First Workflow

on:
    push:
        branches:
            - main
            - dev
    
    pull_request:
        branches:
            - main
            - dev

jobs:
    test-env:
        runs-on: ubuntu-latest
    
        steps:
            - name: checkout code
              uses: actions/checkout@v3
        
            - name: Run Test
              run: |
                    npm test
    
    test-env2:
        runs-on: ubuntu-latest

        steps:
            - name: Print Hello World
              run: echo "Hello World"
